# The URL the site will be built for
base_url = "/"

title = "Rust Search Extension - The ultimate search extension for Rust"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "inspired-github"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "juice"

[extra]
# Put all your custom variables here
juice_logo_name = "Rust Search Extension"
juice_logo_path = "logo.png"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/huhu/rust-search-extension"}
]
meta_title = "Rust Search Extension: The ultimate search extension for Rust"
meta_description = "Search docs, crates, builtin attributes, official books, and error codes, etc in your address bar instantly."